# Generated by Django 4.0.4 on 2022-04-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_content', models.TextField()),
                ('project_published', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
