# Generated by Django 4.0.4 on 2022-05-05 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_link',
            field=models.URLField(default=uuid.uuid1, max_length=128, unique=True),
        ),
    ]
