# Generated by Django 4.0.4 on 2022-05-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_project_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_image',
        ),
    ]
