# Generated by Django 4.0.4 on 2022-05-05 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_project_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
