# Generated by Django 4.0.4 on 2022-05-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_project_image_project_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
