# Generated by Django 4.0.4 on 2022-05-10 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_body',
            new_name='Body',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_Email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_FirstName',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_LastName',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contact_Subject',
            new_name='Subject',
        ),
    ]
