# Generated by Django 4.0.4 on 2022-05-11 07:04

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_image',
            field=models.ImageField(upload_to='static/images/', validators=[main.validators.validate_file_extension]),
        ),
    ]
